/**
 * Contracts, and the clock that does not run while you are not fighting.
 *
 * See docs/16-contracts-free-agency-managers.md. The thesis: **a fighter's career is decided
 * as much by what they signed as by what they can do** — and the mechanism that makes that
 * true without anybody scripting it is that a contract's terms are fixed while the fighter's
 * worth is not. A deal signed at 22 and honoured at 27 after three finishes is the recurring
 * grievance of the sport, and it falls out of one ratio.
 *
 * The single most important correction the review produced: **contracts are tolled.** The
 * term does not run down while a fighter is injured, suspended, refusing a bout or retired.
 * That is the whole point of the clause in reality, and in the game it kills what would
 * otherwise be a dominant strategy — sitting out to run down a bad deal. Holding out now
 * extends your captivity rather than shortening it, which makes the holdout a gamble instead
 * of a lever.
 */

import { clamp, clamp01 } from '../core/math.js';
import type { GameDay } from '../core/clock.js';
import type { AgreementId, FighterId, PromotionId } from '../core/ids.js';
import { asId } from '../core/ids.js';
import type { Fighter } from '../domain/fighter.js';
import type { Promotion } from '../domain/organisations.js';
import { marketValue } from './money.js';

/**
 * The championship extension.
 *
 * Not the infinite lock the first draft described. The real clause tolls the term while you
 * hold the belt and adds a defined tail after you lose it — and it is *negotiable*, which is
 * why the design's instinct that it must be visible and priced at signing turned out not to
 * be a concession to playability but a description of what actually happens.
 */
export type ChampionshipExtension = 'none' | 'standard';

/** Bouts added after a champion loses the belt, under a standard extension. */
export const EXTENSION_TAIL_BOUTS = 2;
/** Or this many days, whichever comes first. */
export const EXTENSION_TAIL_DAYS = 365;

/** Every deal also expires this long after signing — tolled like everything else. */
export const TERM_DAYS = 36 * 30;

export interface PromotionalAgreement {
  id: AgreementId;
  fighterId: FighterId;
  promotionId: PromotionId;

  /** Thousands, at main-card position. Card position multiplies these. */
  showPurse: number;
  winBonus: number;
  signingBonus: number;
  /** Points on the *event's* revenue, which is why a promotion without a platform cannot grant them. */
  revenuePoints: number;

  fightsOwed: number;
  fightsRemaining: number;

  signedDay: GameDay;
  /** Signed day + TERM_DAYS, pushed out day-for-day by every tolled day. */
  expiresDay: GameDay;
  /** Days the clock has been stopped. Shown, because captivity should be legible. */
  tolledDays: number;

  championshipExtension: ChampionshipExtension;
  /** Sold at signing, not assumed. */
  matchingRights: boolean;
  exclusive: boolean;
  /** Non-title bouts elsewhere permitted per 12 months. 0 unless bought. */
  outsideBouts: number;
  /** Bouts the promotion owes per 12 months. Breach voids the deal. */
  activityGuarantee: number;

  /**
   * What the fighter was worth the day they signed.
   *
   * The key field in the whole document. Everything about grievance, renegotiation and
   * resentment is this number against `marketValue` today — which means the sport's most
   * recurring story is generated by arithmetic rather than by a script.
   */
  valueAtSigning: number;
}

/**
 * Identity for a deal.
 *
 * `salt` exists because fighter and day alone are not unique once the re-paper lands: tearing
 * a deal up and replacing it on the same game day produced the same id, so the replacement
 * silently overwrote the original rather than joining it. That failed loudly in the re-paper
 * tests, and would have shown up in a save as a deal that changed its own terms retroactively.
 *
 * Salted with the terms rather than a counter so it stays a pure function of what was signed.
 * Two genuinely identical deals agreed on the same day by the same fighter are the same deal.
 */
export const agreementId = (fighterId: FighterId, day: GameDay, salt = ''): AgreementId =>
  asId<AgreementId>(`agr_${fighterId}_${day}${salt ? `_${salt}` : ''}`);

// --- Fairness, and the grievance it produces --------------------------------------------------

/**
 * What the fighter is being paid against what they are now worth.
 *
 * 1.0 is fair. Below 0.7 is a fighter with a legitimate complaint; above 1.2 is a promotion
 * that overpaid and knows it.
 *
 * Deliberately **never shown as a number**. Both critics agreed on this from different
 * angles: a ratio needs a paragraph, and a sentence does not. The UI says "you are being paid
 * like a prospect and you are ranked fourth", never "0.68".
 */
export function contractFairness(
  agreement: PromotionalAgreement,
  fighter: Fighter,
  promotion: Promotion,
): number {
  const now = marketValue(fighter, promotion);
  if (now <= 0) return 1;
  return (agreement.showPurse + agreement.winBonus) / now;
}

/** How aggrieved a fighter should be, 0–100, given how far their deal has drifted. */
export function resentmentFrom(fairness: number): number {
  if (fairness >= 0.95) return 0;
  // Steep below 0.7, because that is where a fighter stops grumbling and starts talking.
  return Math.round(clamp01((0.95 - fairness) / 0.6) ** 0.8 * 100);
}

/**
 * Said in words rather than as a ratio.
 *
 * The rule from the review: a hidden or abstract number must surface as a sentence a person
 * can act on, or it is noise dressed as depth.
 */
export function describeFairness(fairness: number): string {
  if (fairness >= 1.2) return 'You are being paid more than you are currently worth, and they know it.';
  if (fairness >= 0.95) return 'The deal still reflects what you are worth.';
  if (fairness >= 0.7) return 'You have outgrown this deal a little. Not enough to make a fuss about yet.';
  if (fairness >= 0.45) return 'You are being paid like the fighter you were when you signed, not the one you are.';
  return 'This deal is now an insult, and everybody in the building knows it.';
}

// --- The clock ---------------------------------------------------------------------------------

/** Reasons a promotional clock stops. All of them extend captivity. */
export type TollReason = 'injured' | 'suspended' | 'refusedBout' | 'retired' | 'holdout';

/**
 * Advance a contract's clock across a span of days, some of which may be tolled.
 *
 * The realism correction, implemented: tolled days push the expiry out day for day, so a
 * fighter who sits out a year is a year further from freedom rather than a year closer.
 */
export function tollAgreement(
  agreement: PromotionalAgreement,
  tolledDays: number,
): PromotionalAgreement {
  if (tolledDays <= 0) return agreement;
  return {
    ...agreement,
    tolledDays: agreement.tolledDays + tolledDays,
    expiresDay: agreement.expiresDay + tolledDays,
  };
}

export interface AgreementStatus {
  /** True when the fighter is free to sign elsewhere. */
  expired: boolean;
  /** Days left on the calendar term, after tolling. */
  daysRemaining: number;
  fightsRemaining: number;
  /** True when the belt is holding them in place. */
  heldByBelt: boolean;
  /** Plain sentence for the hub. */
  summary: string;
}

export function agreementStatus(
  agreement: PromotionalAgreement,
  day: GameDay,
  options: { isChampion?: boolean; beltLostDay?: GameDay } = {},
): AgreementStatus {
  const daysRemaining = Math.max(0, agreement.expiresDay - day);
  const fightsRemaining = Math.max(0, agreement.fightsRemaining);

  // The championship extension: tolled while champion, plus a bounded tail afterwards.
  let heldByBelt = false;
  if (agreement.championshipExtension === 'standard') {
    if (options.isChampion) {
      heldByBelt = true;
    } else if (options.beltLostDay !== undefined) {
      const withinTail = day - options.beltLostDay < EXTENSION_TAIL_DAYS;
      heldByBelt = withinTail && fightsRemaining < EXTENSION_TAIL_BOUTS;
    }
  }

  const expired = !heldByBelt && (daysRemaining <= 0 || fightsRemaining <= 0);

  const summary = heldByBelt
    ? 'You cannot leave while you hold the belt.'
    : fightsRemaining <= 0
      ? 'Your obligations are met. You are a free agent.'
      : fightsRemaining === 1
        ? 'One fight left on the deal. Win it and you can talk to anybody.'
        : `${fightsRemaining} fights left on the deal.`;

  return { expired, daysRemaining, fightsRemaining, heldByBelt, summary };
}

/**
 * Whether this fighter may sign with somebody else right now, and if not, why not.
 *
 * Nothing enforced this. `AgreementStatus.expired` was documented as "true when the fighter is
 * free to sign elsewhere" and **no signing path ever consulted it** — a fighter owing three
 * fights could sign with anyone, which made the fights-remaining countdown on the hub a number
 * with no consequences attached to it.
 *
 * The rule is the one the sport actually runs on: you are held to the deal until it runs out or
 * the promotion lets you go. Offers still *arrive* while you are held — seeing what you are worth
 * is most of the drama of being under a bad contract — they simply cannot be accepted.
 */
export interface SigningEligibility {
  allowed: boolean;
  /** Empty when allowed. Otherwise the sentence the screen shows in place of the button. */
  reason: string;
  /** True when asking for a release is the move, so the UI can offer it. */
  releasable: boolean;
}

export function signingEligibility(input: {
  /** Absent for a genuine free agent with no deal at all. */
  status?: AgreementStatus;
  /** How the incumbent is named in the refusal. */
  incumbentName?: string;
  /** Re-signing with your own promotion is always allowed — that is a renewal, not a jump. */
  targetIsIncumbent?: boolean;
}): SigningEligibility {
  const { status, incumbentName = 'your promotion', targetIsIncumbent = false } = input;

  if (!status || status.expired) return { allowed: true, reason: '', releasable: false };
  if (targetIsIncumbent) return { allowed: true, reason: '', releasable: false };

  // The belt is a stronger hold than the term, and it is worth saying so separately: a champion
  // asking for a release is asking for something nobody has ever been given.
  if (status.heldByBelt) {
    return {
      allowed: false,
      reason: `You cannot leave ${incumbentName} while you hold their belt.`,
      releasable: false,
    };
  }

  const owed =
    status.fightsRemaining === 1
      ? 'one more fight'
      : `${status.fightsRemaining} more fights`;

  return {
    allowed: false,
    reason: `You owe ${incumbentName} ${owed}. You cannot sign elsewhere until the deal is done or they release you.`,
    releasable: true,
  };
}

/**
 * Whether a promotion would let a fighter walk early.
 *
 * A release is not a favour and it is not a formality — it is a promotion deciding that what it
 * still owes you is worth less than the roster spot. So the decision runs on how much they value
 * you against how much of the deal is left: somebody they are building is not going anywhere,
 * somebody they have no plans for is a cost they will happily stop carrying.
 *
 * A champion is never released. Neither is anybody with a single fight left, because at that
 * point the promotion simply books it and the question answers itself.
 */
export function releaseDecision(input: {
  /** 0–100. What the promotion thinks they have in you. */
  standing: number;
  status: AgreementStatus;
  isChampion?: boolean;
}): { released: boolean; reason: string } {
  const { standing, status, isChampion = false } = input;

  if (isChampion || status.heldByBelt) {
    return { released: false, reason: 'Champions do not get released. Defend it or vacate it.' };
  }

  if (status.fightsRemaining <= 1) {
    return {
      released: false,
      reason: 'One fight left. They would rather book it than tear the deal up.',
    };
  }

  /*
   * The bar rises with what is left on the deal. Letting somebody out of two fights is a
   * shrug; letting them out of six is writing off a season of matchmaking, and a promotion
   * only does that for somebody it genuinely has no use for.
   */
  const bar = 28 + Math.min(40, status.fightsRemaining * 6);

  if (standing >= bar) {
    return {
      released: false,
      reason: 'They have plans for you. The answer is no.',
    };
  }

  return {
    released: true,
    reason: 'They are not building around you, and the roster spot is worth more than the deal.',
  };
}

/** Has the promotion kept its side — the only real counter to being shelved. */
export function activityBreach(
  agreement: PromotionalAgreement,
  boutsInLastYear: number,
): boolean {
  return boutsInLastYear < agreement.activityGuarantee;
}

// --- Renegotiation ------------------------------------------------------------------------------

export type RenegotiationTrigger =
  | 'wonTitle'
  | 'threeFinishes'
  | 'longStreak'
  | 'grievance'
  | 'activityBreach';

/**
 * Whether a fighter has standing to reopen the deal.
 *
 * Promoted from a paragraph to a real check because the fun brief was right that a bad
 * contract needs a *visible route out the player can chase*. That is the whole difference
 * between regret and punishment: "three consecutive finishes reopens your deal — you have
 * one" is a goal, where "you signed badly" is a sentence.
 */
export function renegotiationTriggers(
  agreement: PromotionalAgreement,
  fighter: Fighter,
  promotion: Promotion,
  options: { isChampion?: boolean; boutsInLastYear?: number } = {},
): RenegotiationTrigger[] {
  const triggers: RenegotiationTrigger[] = [];

  if (options.isChampion) triggers.push('wonTitle');

  const recent = fighter.record.slice(-3);
  if (
    recent.length === 3 &&
    recent.every((r) => r.outcome === 'win' && r.method !== 'decisionUnanimous' && !r.method.startsWith('decision'))
  ) {
    triggers.push('threeFinishes');
  }

  if (fighter.summary.streak >= 5) triggers.push('longStreak');
  if (contractFairness(agreement, fighter, promotion) < 0.55) triggers.push('grievance');
  if (options.boutsInLastYear !== undefined && activityBreach(agreement, options.boutsInLastYear)) {
    triggers.push('activityBreach');
  }

  return triggers;
}

export function describeTrigger(trigger: RenegotiationTrigger): string {
  switch (trigger) {
    case 'wonTitle':
      return 'You are the champion. That reopens everything.';
    case 'threeFinishes':
      return 'Three finishes in a row. They cannot pretend they have not noticed.';
    case 'longStreak':
      return 'Five straight wins. The deal was written for a different fighter.';
    case 'grievance':
      return 'You are being paid a fraction of what you are now worth.';
    case 'activityBreach':
      return 'They owe you fights they have not booked. That is their side of the deal, not yours.';
  }
}

// --- Building a deal ----------------------------------------------------------------------------

export interface OfferTerms {
  showPurse: number;
  winBonus: number;
  signingBonus: number;
  revenuePoints: number;
  fightsOwed: number;
  championshipExtension: ChampionshipExtension;
  matchingRights: boolean;
  exclusive: boolean;
  outsideBouts: number;
}

/**
 * What each term is worth to a fighter, so an offer can be compared as a whole.
 *
 * Every term here is *priced*, which was the fun brief's central complaint about the draft:
 * an unpriced term is not a decision, it is a slider with one correct setting. Fights owed
 * costs the promotion money because length is worth something to them; matching rights are
 * sold rather than assumed; the extension is buyable out.
 */
export const TERM_PRICING = {
  /** Each fight beyond the first adds this share to the show purse. */
  perExtraFight: 0.06,
  /** What the fighter is paid for granting matching rights. */
  matchingRights: 0.12,
  /** What buying out the championship extension costs, as a share of show purse. */
  extensionBuyout: 0.15,
  /** What each permitted outside bout costs the fighter, as a share. */
  perOutsideBout: 0.08,
} as const;

/** Cap on how long a deal can be. Longer than this stops being regret and becomes a debuff. */
export const MAX_FIGHTS_OWED = 6;

export function createAgreement(input: {
  fighter: Fighter;
  promotion: Promotion;
  terms: OfferTerms;
  day: GameDay;
}): PromotionalAgreement {
  const { fighter, promotion, terms, day } = input;
  const fights = clamp(Math.round(terms.fightsOwed), 1, MAX_FIGHTS_OWED);

  return {
    id: agreementId(fighter.id, day, `${terms.showPurse}x${fights}`),
    fighterId: fighter.id,
    promotionId: promotion.id,
    showPurse: terms.showPurse,
    winBonus: terms.winBonus,
    signingBonus: terms.signingBonus,
    revenuePoints: promotion.revenueShareCapable ? terms.revenuePoints : 0,
    fightsOwed: fights,
    fightsRemaining: fights,
    signedDay: day,
    expiresDay: day + TERM_DAYS,
    tolledDays: 0,
    championshipExtension: terms.championshipExtension,
    matchingRights: terms.matchingRights,
    exclusive: terms.exclusive,
    outsideBouts: terms.outsideBouts,
    activityGuarantee: promotion.activityGuarantee,
    valueAtSigning: marketValue(fighter, promotion),
  };
}

/** Burn a fight off the deal. Returns the agreement unchanged when nothing is owed. */
export function consumeFight(agreement: PromotionalAgreement): PromotionalAgreement {
  if (agreement.fightsRemaining <= 0) return agreement;
  return { ...agreement, fightsRemaining: agreement.fightsRemaining - 1 };
}

// --- Release ------------------------------------------------------------------------------------

/**
 * Whether a promotion cuts a fighter.
 *
 * The realism correction: release is an **at-will** clause, not a losses trigger. "Three
 * straight and you are gone" is a convention applied unevenly — exciting fighters survive
 * 0-3 and boring winners get cut — and that unevenness is the more interesting truth. Star
 * power buys patience that a good record does not.
 */
export function releaseRisk(fighter: Fighter, promotion: Promotion): number {
  const skid = Math.max(0, -fighter.summary.streak);
  if (skid === 0) return 0;

  // Two losses is a conversation. Three is usually the end, unless they sell tickets.
  const base = clamp01((skid - 1) / 3);
  const draw = clamp01(fighter.starPower / 100);
  // A promotion that pushes its own faces protects them for longer.
  const patience = 0.35 + draw * 0.75 + (promotion.narrativeControl / 100) * 0.2;

  return clamp01(base / patience) * 0.75;
}

export function describeReleaseRisk(risk: number): string {
  if (risk <= 0) return 'Your place is not in question.';
  if (risk < 0.2) return 'One more bad night and it becomes a conversation.';
  if (risk < 0.45) return 'You are fighting for your job and everybody knows it.';
  return 'You are almost certainly gone if you lose this.';
}

// --- The re-paper -------------------------------------------------------------------------------

/**
 * "We'll rip that up. More money, starting now."
 *
 * Doc 16 specifies this in full and nothing implemented it, which left the contract layer
 * with only one shape of decision — sign, then endure until it expires. The re-paper is the
 * mechanism that turns captivity into something you agreed to repeatedly, and it is the
 * honest near-neighbour of the champion's-clause sensation the fun brief asked for. An
 * automatic per-win extension is not a term that exists; tearing up a deal and replacing it
 * after a good win is everywhere in the sport.
 *
 * More money today for more captivity tomorrow, offered at the exact moment you feel
 * invincible. Refusing costs nothing except that the offer may not return at that price.
 * Accepting is how a career gets quietly extended by four years.
 *
 * The important structural consequence: `MAX_FIGHTS_OWED` is not really a cap on how long
 * you can be trapped. It is a cap on how long you can be trapped *without having said yes
 * again* — which is a far more interesting thing to be true.
 */

/** Minimum straight wins before a promotion will tear up a deal. */
export const REPAPER_MIN_STREAK = 2;

export interface RepaperOffer {
  /** The replacement terms, ready to be signed. */
  terms: OfferTerms;
  /** What the fighter is on now, for the comparison the screen has to show. */
  current: { showPurse: number; winBonus: number; fightsRemaining: number };
  /** Fractional uplift on show purse, 0.25–0.40. */
  uplift: number;
  /** Why it is being offered, in the promotion's words. */
  reason: string;
}

/**
 * Whether the promotion tears up the deal, and on what terms.
 *
 * Fires on a win streak rather than on any single win, because "after every win" is both
 * wrong and exhausting — a promotion does not reopen a deal for a fighter who has just beaten
 * a debutant. Undefined means no offer, which is the common case.
 *
 * The uplift is scaled by how badly the current deal has fallen behind what the fighter is
 * worth. That is deliberate: a promotion re-papers precisely when the gap has become
 * embarrassing enough that somebody else would pay it, so the size of the offer is a readout
 * of how underpaid you already were.
 */
export function repaperOffer(input: {
  agreement: PromotionalAgreement;
  fighter: Fighter;
  promotion: Promotion;
  /** True when the win that triggered this was for a belt. */
  wasTitleFight?: boolean;
}): RepaperOffer | undefined {
  const { agreement, fighter, promotion, wasTitleFight } = input;

  if (agreement.fightsRemaining <= 0) return undefined;

  /*
   * Not on a deal they have not fought on yet.
   *
   * Without this the offer re-fires the instant it is accepted, because a single 25–40% rise
   * does not always close the whole gap for a fighter who has grown a lot — so the player
   * would be handed the same alert repeatedly and could ratchet their purse upward without
   * ever stepping in a cage. The re-paper is payment for having won; it has to be earned again
   * each time.
   */
  if (agreement.fightsRemaining >= agreement.fightsOwed) return undefined;

  const streak = fighter.summary.streak;
  if (streak < REPAPER_MIN_STREAK && !wasTitleFight) return undefined;

  // How far behind the deal has fallen. 1.0 means it is still fair.
  const fairness = contractFairness(agreement, fighter, promotion);
  const behind = clamp01(1 - fairness);

  // A promotion does not reopen a deal that is still fair, however long the streak.
  if (behind < 0.15 && !wasTitleFight) return undefined;

  const uplift = clamp(0.25 + behind * 0.35, 0.25, 0.4);
  const fightsOwed = clamp(
    Math.round(4 + behind * 2),
    4,
    MAX_FIGHTS_OWED,
  );

  return {
    uplift,
    current: {
      showPurse: agreement.showPurse,
      winBonus: agreement.winBonus,
      fightsRemaining: agreement.fightsRemaining,
    },
    terms: {
      showPurse: round1(agreement.showPurse * (1 + uplift)),
      winBonus: round1(agreement.winBonus * (1 + uplift)),
      signingBonus: 0,
      revenuePoints: agreement.revenuePoints,
      fightsOwed,
      // Reattached rather than carried over. The whole trade is more money now for terms
      // that bind you again, and quietly dropping the extension would make it a free raise.
      championshipExtension: agreement.championshipExtension === 'none' ? 'standard' : agreement.championshipExtension,
      matchingRights: agreement.matchingRights,
      exclusive: agreement.exclusive,
      outsideBouts: agreement.outsideBouts,
    },
    reason: wasTitleFight
      ? `${promotion.shortName} want their champion on a champion's deal.`
      : `${streak} straight. ${promotion.shortName} would rather pay you now than lose you later.`,
  };
}

/**
 * Accept a re-paper: tear the old deal up and replace it.
 *
 * A genuinely new agreement rather than an edit, because `valueAtSigning` has to be restamped
 * — that field is what every future grievance is measured against, and carrying the old one
 * forward would mean a fighter who re-papered at 90 was still nursing a grudge calibrated to
 * what they were worth at 30.
 */
export function acceptRepaper(input: {
  agreement: PromotionalAgreement;
  offer: RepaperOffer;
  fighter: Fighter;
  promotion: Promotion;
  day: GameDay;
}): PromotionalAgreement {
  const { offer, fighter, promotion, day } = input;
  return createAgreement({ fighter, promotion, terms: offer.terms, day });
}

const round1 = (n: number): number => Math.round(n * 10) / 10;
